services:
  - type: web
    name: 86connect-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: PORT
        value: "3001"
      - key: RESEND_API_KEY
        sync: false
      - key: NOTIFY_EMAIL
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_FOLDER
        sync: false